---
<<<<<<< HEAD
title: "Anomaly Detection: Credit Card Fraud Detection"
subtitle: "Proposal"
author: 
  - name: "Reilly Rodriguez Spencer"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "Proposal for using unsupervised machine learning and statistical techniques to detect anomalies in credit card transaction data."
=======
title: "Proposal title"
subtitle: "Proposal"
author: 
  - name: "Team Name - Team member 1, Team member 2,..."
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "Project description"
>>>>>>> upstream/main
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
<<<<<<< HEAD
#| echo: false
import pandas as pd
=======
#| message: false
>>>>>>> upstream/main
import numpy as np
```

## Dataset

```{python}
#| label: load-dataset
<<<<<<< HEAD
#| echo: false
df = pd.read_csv("data/creditcard.csv")
df_shape = df.shape
df_preview = df.head()
```

The dataset used is the Credit Card Fraud Detection dataset from Kaggle, which contains r df_shape[0] rows and r df_shape[1] columns of anonymized transaction data from European cardholders in 2013.
I chose this dataset because it is highly imbalanced with 0.172% of transactions being fraudulent cases. This makes it an excellent candidate for anomaly detection techniques.


## Questions

1. 
2. 

## Analysis plan

- Data Preprocessing
    - August 6 to August 7
- Modeling: Unsupervised learning
    - August 8 to August 10
- Evaluation
    - August 11 to August 13
- Visualization
    - August 13 to August 16
- Presentation prep 
    - August 17 to August 19
=======
#| message: false
```

A brief description of your dataset including its provenance, dimensions, etc. as well as the reason why you chose this dataset.

Make sure to load the data and use inline code for some of this information.

## Questions

The two questions you want to answer.

## Analysis plan

-   A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).
>>>>>>> upstream/main
